FROM nginx:1.13.5

RUN apt-get update && apt-get install -y --no-install-recommends jekyll node-less

RUN mkdir /code
WORKDIR /code
COPY . /code

RUN jekyll build -s labs.acousticbrainz.org -d  /usr/share/nginx/html
RUN lessc /usr/share/nginx/html/static/css/main.less /usr/share/nginx/html/static/css/main.css

COPY nginx.conf /etc/nginx/nginx.conf

